### ISSUE TITLE
@State variables doesn't update GifView.

### ISSUE THREAD

**Issue by OguzYuuksel** [SimformSolutionsPvtLtd/SSSwiftUIGIFView#3]
When you try to update gif with a @State, it doesn't work.

**Comment by iftikharokz** [comment]
Same issue [OguzYuuksel](https://github.com/OguzYuuksel) how did you solved the issue

**Comment by YagnikBavishi04** [comment]
Fixed by #8

**Comment by YagnikBavishi04** [comment]
We have Fixed issue in [2.0.0](https://github.com/SimformSolutionsPvtLtd/SSSwiftUIGIFView/releases/tag/2.0.0).
