### ISSUE TITLE
Add Swift Package Manager

### ISSUE THREAD

**Issue by afern247** [SimformSolutionsPvtLtd/SSSwiftUIGIFView#4]
Hi, I have my whole project with SPM, could you please add an option to add it?

Thank you

**Comment by Dave181295** [comment]
Yes please

**Comment by YagnikBavishi04** [comment]
We have Added Support for SPM in [2.0.0](https://github.com/SimformSolutionsPvtLtd/SSSwiftUIGIFView/releases/tag/2.0.0).
