### ISSUE TITLE
SwiftGif still saying: This image named "loading.gif" does not exist

### ISSUE THREAD

**Issue by tommassbrand** [SimformSolutionsPvtLtd/SSSwiftUIGIFView#5]
I tried to put image in the same folder as view where I want to use the gif, I tried to remove or add ".gif" here `SwiftUIGIFPlayerView(gifName: "loading")` but still same result a it does not work. Same gif I used in UIKit, so gif file is correct.

**Comment by zizlak** [comment]
Check if you added file to the target

**Comment by YagnikBavishi04** [comment]
@zizlak is right. @tommassbrand  Please check gif is added in the proper target or not.
